##
## Simple buildup configuration file for the Magnum-CI service 
## (https://magnum-ci.com/docs/configuration)
##
##

# **Note**
# If you want to run this buildup only on some branches you can select them in settings of your project
# (Settings -> Build Configuration).

install:
    # update sources
    - sudo apt-get clean
    - sudo apt-get autoclean
    - sudo apt-get update
    # install software
    - sudo apt-get install gfortran make cmake libblas-dev liblapack-dev python-pip python-setuptools python-dev -y
    # install Python packages with pip
    - sudo pip install pytest

script:
# show CPU info
    - lscpu
    #- echo " number of procs at this machine : $(cat /proc/cpuinfo | grep processor | wc -l)"
# configure and build
    - python ./setup.py --fc=gfortran --cmake-options="--no-warn-unused-cli -DMATH_LIB_SEARCH_ORDER='SYSTEM_NATIVE;ATLAS' -D BUILDNAME='magnum_gfortran'" || true
    - cd build
    - make VERBOSE=1 Experimental
    - ldd bin/example
    - bin/example
