language: cpp
install:
    # update, clean
  - sudo apt-get update
  - sudo apt-get autoclean
  - sudo apt-get clean
    # compilers
  - sudo apt-get install g++ cmake gfortran
    # math libraries
  - sudo apt-get install libatlas-base-dev libatlas-dev
  - sudo apt-get install libopenblas-dev libopenblas-base
    # PEP8 and py.test
  - sudo pip install pytest pep8
script:
  - python ./setup.py --fc=gfortran --cmake-options='--no-warn-unused-cli -DMATH_LIB_SEARCH_ORDER="OPENBLAS;ATLAS;SYSTEM_NATIVE;MKL"  -D BUILDNAME="travis"' || true
  - cd build
  - make VERBOSE=1 Experimental
    # show dependencies
  - ldd bin/example
    #  run test (should end with 0)
  - cd bin
  - ls -lt
  ##- exec "./example"


# turn off email notifications
notifications:
  email: false
