language: cpp
install:
    # compilers
  - sudo apt-get install g++ cmake gfortran
    # math libraries
  - sudo apt-get install libblas-dev liblapack-dev
    # MPI
  - sudo apt-get install openmpi-bin libopenmpi-dev
    # PEP8 and py.test
  - sudo pip install pytest pep8
script:
  - python ./setup.py --fc=gfortran
  - cd build
  - make
  - bin/example 100 1
