language: cpp
install:
    # update, clean
  - sudo apt-get update
  - sudo apt-get autoclean
  - sudo apt-get clean
    # compilers
  - sudo apt-get install g++ cmake gfortran
    # math libraries
  - sudo apt-get install libatlas-base-dev libatlas-dev
  - sudo apt-get install libopenblas-dev libopenblas-base
    # PEP8 and py.test
  - sudo pip install pytest pep8
script:
  - python ./setup.py --fc=gfortran --cmake-options='-DMATH_LIB_SEARCH_ORDER="OPENBLAS;ATLAS;SYSTEM_NATIVE;MKL"'
  - cd build
  - make VERBOSE=1: { pwd: build }
    # show dependencies
  - ldd bin/example: { pwd: build } 
    #  run test (should end with 0)
  - bin/example: { pwd: build }

# turn off email notifications
notifications:
  email: false
